### ISSUE TITLE
After fixing your vehicle fuel shows 65

### ISSUE THREAD

**Issue by Nidelix** [InZidiuZ/LegacyFuel#18]
Hi,

This a bug report. When you fill up you vehicle tank to 100 and you use fixkit to repair your vehicle. The fuel meter shows to you 65.

**Comment by InZidiuZ** [comment]
ESX's "fixkit" item?

**Comment by ponduzn** [comment]
> ESX's "fixkit" item?

That and mechanic repair menu function :)

**Comment by Nidelix** [comment]
And I found one more bug :) Server fuel update. When you are driving and fuel meter show that is empty and you companion traveller jumps into driver's seat and VOLá the car has his/her fuel. Short story, server update fuel is a buggy.

**Comment by InZidiuZ** [comment]
There's no "server fuel update". It uses decors to sync up between the clients. Although, I do believe I pushed a fix for the syncing issues yesterday. So make sure you're on the latest version, @Nidelix.

**Comment by ponduzn** [comment]
> There's no "server fuel update". It uses decors to sync up between the clients. Although, I do believe I pushed a fix for the syncing issues yesterday. So make sure you're on the latest version, @Nidelix.

I am on the latest update, still happens here atleast mate.

**Comment by Nidelix** [comment]
@InZidiuZ Thanks m8. I will try.

**Comment by InZidiuZ** [comment]
Just investigated this, and it seems to be because of the `SetVehicleFixed` native. Not going create any workarounds for it in the this script, so you'll have to insert a manual workaround into the [esx_mechanicjob](https://github.com/ESX-Org/esx_mechanicjob) resource.

**To fix it:**
1) Look for the client-sided event called 'esx_mechanicjob:onFixkit'
2) Find where it calls for `SetVehicleFixed(vehicle)`
3) Insert two exports to get the current fuel just before the vehicle is "fixed", as well as setting it back to the old one after it has been fixed and reset.

**Old:**
```
SetVehicleFixed(vehicle)
```

**New:**
```
local fuel = exports["LegacyFuel"]:GetFuel(vehicle)
SetVehicleFixed(vehicle)
exports["LegacyFuel"]:SetFuel(vehicle, fuel)
```
